# Generated by Django 5.1.5 on 2025-03-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ingredient_name_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
