# Generated by Django 5.1.5 on 2025-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
