# Generated by Django 5.1.5 on 2025-03-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
